# Generated by Django 2.0 on 2017-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='vidia.Tag'),
        ),
    ]
