# Generated by Django 2.0 on 2017-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidia', '0002_auto_20171205_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='vidia.Tag'),
        ),
    ]
